version: '2'
services:

  cluster-master:
    image: outcoldman/splunk-cluster:6.4.2
    container_name: cluster-master
    hostname: cluster-master
    depends_on:
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_master
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_REPLICATION_FACTOR=1
      - INIT_CLUSTERING_SEARCH_FACTOR=1
      - INIT_CLUSTERING_CLUSTER_LABEL=cluster
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_WEB_ENABLED=true
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "cluster-master"
    networks:
      splunk:
        aliases:
          - cluster-master
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-deployer:
    image: outcoldman/splunk-cluster:6.4.2
    container_name: shc-deployer
    hostname: shc-deployer
    depends_on:
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=shc_deployer
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "shc-deployer"
    networks:
      splunk:
        aliases:
          - shc-deployer
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-member:
    image: outcoldman/splunk-cluster:6.4.2
    depends_on:
      - shc-deployer
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=shc_member,shc_deployer_client,cluster_searchhead
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_SHCLUSTERING_SHCDEPLOYER=https://shc-deployer:8089
      - INIT_SHCLUSTERING_REPLICATION_FACTOR=3
      - INIT_SHCLUSTERING_SHCLUSTER_LABEL=shcluster
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_SHCLUSTER_AUTOBOOTSTRAP=3
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "shc-member"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  cluster-slave:
    image: outcoldman/splunk-cluster:6.4.2
    depends_on:
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_slave
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "cluster-slave"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  dmc:
    image: outcoldman/splunk-cluster:6.4.2
    container_name: dmc
    hostname: dmc
    depends_on:
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_searchhead,dmc
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_KVSTORE_ENABLED=false
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "dmc"
    networks:
      splunk:
        aliases:
          - dmc
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  consul:
    image: outcoldman/splunk-cluster:6.4.2-consul
    container_name: consul
    hostname: consul
    restart: always
    networks:
      splunk:
        aliases:
          - consul
    labels:
      splunk.cluster: "consul"
    environment:
      - CONSUL_DATA_DIR=/consul/data
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_CLIENT=0.0.0.0
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_JOIN=consul
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - SYSLOG_SERVER=hw_forwarder
      - SYSLOG_PORT=1514
      - SYSLOG_PROTO=udp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  hw-forwarder:
    image: outcoldman/splunk-cluster:6.4.2
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=hw_forwarder
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_ADD_UDP_PORT=1514
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    networks:
      splunk:
        aliases:
          - hw_forwarder
    labels:
      splunk.cluster: "hw-forwarder"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  lb:
    image: outcoldman/splunk-cluster:6.4.2-lb
    container_name: lb
    hostname: lb
    depends_on:
      - consul
      - hw-forwarder
    environment: 
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - SYSLOG_SERVER=hw_forwarder
      - SYSLOG_PORT=1514
      - SYSLOG_PROTO=udp
    labels:
      splunk.cluster: "lb"
    networks:
      splunk:
        aliases:
          - lb
    restart: always
    ports:
      - 8000:8000
      - 8100:8100
      - 8200:8200
      - 8300:8300
      - 8500:8500
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

networks:
  splunk: