version: '2'
services:

  cluster-master:
    image: ${SPLUNK_CLUSTER_DOCKER_IMAGE_PATH}/splunk-cluster:${SPLUNK_CLUSTER_VERSION}
    container_name: cluster-master
    hostname: cluster-master
    depends_on:
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_ROLES=cluster_master,shc_deployer,dmc,deployment_server
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_REPLICATION_FACTOR=3
      - INIT_CLUSTERING_SEARCH_FACTOR=2
      - INIT_CLUSTERING_CLUSTER_LABEL=cluster
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_SHCLUSTERING_SHCLUSTER_LABEL=shcluster
      - INIT_DEPLOYMENT_PASS_4_SYMM_KEY=deployment-changeme
      - INIT_DEPLOYMENT_REQUIRE_AUTHENTICATION=true
      - INIT_DEPLOYMENT_CROSS_SERVER_CHECKSUM=true
      - INIT_DEPLOYMENT_SERVER_PUBLIC=true
      - INIT_ENABLE_HTTP_EVENT_COLLECTOR=true
      - INIT_HTTP_EVENT_COLLECTOR_TOKEN=EF211A51-D6AC-4045-8CD6-F730939AC518
      - INIT_SERVERCLASS_HTTP_EVENT_COLLECTOR=data-collector-hec
      - INIT_CONF__web__settings__login_content=Cluster Master
      - INIT_CONF__server__general__serverName=cluster-master
      - INIT_CONF__inputs__default__host=cluster-master
      - INIT_CONF__server__kvstore__disabled=true
      - INIT_FORWARD_INDEX=true
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "cluster-master"
    networks:
      splunk:
        aliases:
          - cluster-master
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-member:
    image: ${SPLUNK_CLUSTER_DOCKER_IMAGE_PATH}/splunk-cluster:${SPLUNK_CLUSTER_VERSION}
    depends_on:
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_ROLES=shc_member,shc_deployer_client,cluster_searchhead
      - INIT_SHCLUSTERING_SHCDEPLOYER=https://cluster-master:8089
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_SHCLUSTERING_REPLICATION_FACTOR=3
      - INIT_SHCLUSTERING_SHCLUSTER_LABEL=shcluster
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_SHCLUSTER_AUTOBOOTSTRAP=3
      - INIT_CONF__server__shclustering__election_timeout_ms=5000
      - INIT_CONF__web__settings__login_content=SHC Member
      - INIT_CONF__splunk_management_console__app__install__state=disabled
      - INIT_FORWARD_INDEX=true
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "shc-member"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  cluster-slave:
    image: ${SPLUNK_CLUSTER_DOCKER_IMAGE_PATH}/splunk-cluster:${SPLUNK_CLUSTER_VERSION}
    depends_on:
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_ROLES=cluster_slave,deployment_client,data_collector
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_DEPLOYMENT_PASS_4_SYMM_KEY=deployment-changeme
      - INIT_DEPLOYMENT_CLIENT_NAME=data-collector-hec
      - INIT_DEPLOYMENT_CLIENT_DEPLOYMENT_SERVER=cluster-master:8089
      - INIT_REGISTER_PUBLIC_HTTP_EVENT_COLLECTOR=true
      - INIT_ADD_UDP_PORT=1514
      - INIT_CONF__splunk_management_console__app__install__state=disabled
      - INIT_CONF__server__kvstore__disabled=true
      - INIT_CONF__web__settings__startwebserver=false
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "cluster-slave"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  consul:
    image: ${SPLUNK_CLUSTER_DOCKER_IMAGE_PATH}/splunk-cluster-consul:${SPLUNK_CLUSTER_VERSION}
    container_name: consul
    hostname: consul
    restart: always
    networks:
      splunk:
        aliases:
          - consul
    labels:
      splunk.cluster: "consul"
    environment:
      - CONSUL_DATA_DIR=/var/consul/data
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_CLIENT=0.0.0.0
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_JOIN=consul
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - SYSLOG_SERVER=cluster-slave
      - SYSLOG_PORT=1514
      - SYSLOG_PROTO=udp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  lb:
    image: ${SPLUNK_CLUSTER_DOCKER_IMAGE_PATH}/splunk-cluster-lb:${SPLUNK_CLUSTER_VERSION}
    container_name: lb
    hostname: lb
    depends_on:
      - consul
    environment: 
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - SYSLOG_SERVER=cluster-slave
      - SYSLOG_PORT=1514
      - SYSLOG_PROTO=udp
    labels:
      splunk.cluster: "lb"
    networks:
      splunk:
        aliases:
          - lb
    restart: always
    ports:
      - 8000:8000
      - 8010:8010
      - 8500:8500
      - 8089:8089
      - 8088:8088
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

networks:
  splunk: