version: '2'
services:

  cluster-master:
    image: outcoldman/splunk-cluster:latest
    container_name: cluster-master
    hostname: cluster-master
    depends_on:
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_master
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_REPLICATION_FACTOR=1
      - INIT_CLUSTERING_SEARCH_FACTOR=1
      - INIT_CLUSTERING_CLUSTER_LABEL=cluster
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_WEB_ENABLED=true
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "cluster-master"
    networks:
      splunk:
        aliases:
          - cluster-master
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-deployer:
    image: outcoldman/splunk-cluster:latest
    container_name: shc-deployer
    hostname: shc-deployer
    depends_on:
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=shc_deployer
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "shc-deployer"
    networks:
      splunk:
        aliases:
          - shc-deployer
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-member:
    image: outcoldman/splunk-cluster:latest
    depends_on:
      - shc-deployer
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=shc_member,shc_deployer_client,cluster_searchhead
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_SHCLUSTERING_SHCDEPLOYER=https://shc-deployer:8089
      - INIT_SHCLUSTERING_REPLICATION_FACTOR=3
      - INIT_SHCLUSTERING_SHCLUSTER_LABEL=shcluster
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_SHCLUSTER_AUTOBOOTSTRAP=3
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "shc-member"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  cluster-slave:
    image: outcoldman/splunk-cluster:latest
    depends_on:
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_slave
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "cluster-slave"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  dmc:
    image: outcoldman/splunk-cluster:latest
    container_name: dmc
    hostname: dmc
    depends_on:
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_searchhead,dmc
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_KVSTORE_ENABLED=false
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "dmc"
    networks:
      splunk:
        aliases:
          - dmc
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  deployment-server:
    image: outcoldman/splunk-cluster:latest
    container_name: deployment-server
    hostname: deployment-server
    depends_on:
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=deployment_server
      - INIT_DEPLOYMENT_PASS_4_SYMM_KEY=deployment-changeme
      - INIT_DEPLOYMENT_REQUIRE_AUTHENTICATION=true
      - INIT_DEPLOYMENT_CROSS_SERVER_CHECKSUM=true
      - INIT_DEPLOYMENT_SERVER_PUBLIC=true
      - INIT_ENABLE_HTTP_EVENT_COLLECTOR=true
      - INIT_HTTP_EVENT_COLLECTOR_TOKEN=EF211A51-D6AC-4045-8CD6-F730939AC518
      - INIT_SERVERCLASS_HTTP_EVENT_COLLECTOR=data-collector-hec
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    labels:
      splunk.cluster: "deployment-server"
    networks:
      splunk:
        aliases:
          - deployment-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  consul:
    image: outcoldman/splunk-cluster:latest-consul
    container_name: consul
    hostname: consul
    restart: always
    networks:
      splunk:
        aliases:
          - consul
    labels:
      splunk.cluster: "consul"
    environment:
      - CONSUL_DATA_DIR=/var/consul/data
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_CLIENT=0.0.0.0
      - CONSUL_BOOTSTRAP_EXPECT=1
      - CONSUL_JOIN=consul
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - SYSLOG_SERVER=data-collector-internal
      - SYSLOG_PORT=1514
      - SYSLOG_PROTO=udp
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  data-collector-internal:
    image: outcoldman/splunk-cluster:latest
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=data_collector,deployment_client
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_ADD_UDP_PORT=1514
      - INIT_DEPLOYMENT_PASS_4_SYMM_KEY=deployment-changeme
      - INIT_DEPLOYMENT_CLIENT_NAME=data-collector-internal
      - INIT_DEPLOYMENT_CLIENT_DEPLOYMENT_SERVER=deployment-server:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    networks:
      splunk:
        aliases:
          - data-collector-internal
    labels:
      splunk.cluster: "data-collector-internal"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  data-collector-hec:
    image: outcoldman/splunk-cluster:latest
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=data_collector,deployment_client
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_DEPLOYMENT_PASS_4_SYMM_KEY=deployment-changeme
      - INIT_DEPLOYMENT_CLIENT_NAME=data-collector-hec
      - INIT_DEPLOYMENT_CLIENT_DEPLOYMENT_SERVER=deployment-server:8089
      - INIT_REGISTER_PUBLIC_HTTP_EVENT_COLLECTOR=true
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
    networks:
      - splunk
    labels:
      splunk.cluster: "data-collector-hec"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  lb:
    image: outcoldman/splunk-cluster:latest-lb
    container_name: lb
    hostname: lb
    depends_on:
      - consul
      - data-collector-internal
    environment: 
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - CONSUL_ADVERTISE_INTERFACE=eth0
      - SYSLOG_SERVER=data-collector-internal
      - SYSLOG_PORT=1514
      - SYSLOG_PROTO=udp
    labels:
      splunk.cluster: "lb"
    networks:
      splunk:
        aliases:
          - lb
    restart: always
    ports:
      - 8000:8000
      - 8010:8010
      - 8020:8020
      - 8030:8030
      - 8040:8040
      - 8500:8500
      - 8089:8089
      - 8088:8088
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

networks:
  splunk: