version: '2'
services:

  cluster-master:
    environment: 
      - SPLUNK_ROLES=license_master,deployment_server
      - INIT_WAIT_LICENSE=true
      - CONF__server__general__pass4SymmKey=general-changeme

  shc-member:
    environment: 
      - SPLUNK_ROLES=shc_member
      - INIT_WAIT_SPLUNK_license_master=https://cluster-master:8089,license_master
      - CONF__server__general__pass4SymmKey=general-changeme
      - CONF__server__license__master_uri=https://cluster-master:8089

  cluster-slave:
    environment: 
      - SPLUNK_ROLES=data_collector
      - INIT_WAIT_SPLUNK_license_master=https://cluster-master:8089,license_master
      - CONF__server__general__pass4SymmKey=general-changeme
      - CONF__server__license__master_uri=https://cluster-master:8089