version: '2'
services:

  license-master:
    build: ./node/
    container_name: license-master
    hostname: license-master
    depends_on:
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=license_master
      - INIT_GENERAL_PASS_4_SYMM_KEY=general-changeme
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
    labels:
      splunk.cluster: "license-master"
    networks:
      splunk:
        aliases:
          - license-master
    ports:
      - 8000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  cluster-master:
    build: ./node/
    container_name: cluster-master
    hostname: cluster-master
    depends_on:
      - license-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_master,license_slave
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_REPLICATION_FACTOR=1
      - INIT_CLUSTERING_SEARCH_FACTOR=1
      - INIT_CLUSTERING_CLUSTER_LABEL=cluster1
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_GENERAL_PASS_4_SYMM_KEY=general-changeme
      - INIT_LICENSE_MASTER=https://license-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
    labels:
      splunk.cluster: "cluster-master"
    networks:
      splunk:
        aliases:
          - cluster-master
    ports:
      - 8000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-deployer:
    build: ./node/
    container_name: shc-deployer
    hostname: shc-deployer
    depends_on:
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=shc_deployer
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
    labels:
      splunk.cluster: "shc-deployer"
    networks:
      splunk:
        aliases:
          - shc-deployer
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-member:
    build: ./node/
    depends_on:
      - shc-deployer
      - license-master
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=shc_member,shc_deployer_client,license_slave,cluster_searchhead
      - INIT_SHCLUSTERING_PASS_4_SYMM_KEY=shclustering-changeme
      - INIT_SHCLUSTERING_SHCDEPLOYER=https://shc-deployer:8089
      - INIT_SHCLUSTERING_REPLICATION_FACTOR=3
      - INIT_SHCLUSTERING_SHCLUSTER_LABEL=shcluster1
      - INIT_GENERAL_PASS_4_SYMM_KEY=general-changeme
      - INIT_LICENSE_MASTER=https://license-master:8089
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
    labels:
      splunk.cluster: "shc-member"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  cluster-slave:
    build: ./node/
    depends_on:
      - cluster-master
      - license-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_slave,license_slave
      - INIT_GENERAL_PASS_4_SYMM_KEY=general-changeme
      - INIT_LICENSE_MASTER=https://license-master:8089
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
    labels:
      splunk.cluster: "cluster-slave"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  dmc:
    build: ./node/
    container_name: dmc
    hostname: dmc
    depends_on:
      - license-master
      - cluster-master
      - consul
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=license_slave,cluster_searchhead
      - INIT_CLUSTERING_PASS_4_SYMM_KEY=clustering-changeme
      - INIT_CLUSTERING_CLUSTER_MASTER=https://cluster-master:8089
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - INIT_GENERAL_PASS_4_SYMM_KEY=general-changeme
      - INIT_LICENSE_MASTER=https://license-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
    labels:
      splunk.cluster: "dmc"
    networks:
      splunk:
        aliases:
          - dmc
    ports:
      - 8000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  consul:
    image: consul:v0.6.4
    container_name: consul
    hostname: consul
    restart: always
    networks:
      splunk:
        aliases:
          - consul
    command:
      - agent
      - -bootstrap
      - -data-dir=/consul/data
      - -dc=dc
      - -domain=splunk
      - -server
      - -ui
      - -client=0.0.0.0
    ports:
      - 8500
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  hw_forwarder:
    build: ./node/
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=hw_forwarder
      - INIT_INDEX_DISCOVERY_PASS_4_SYMM_KEY=indexdiscovery-changeme
      - INIT_INDEX_DISCOVERY_MASTER_URI=https://cluster-master:8089
      - CONSUL_HOST=consul
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
      - INIT_ADD_UDP_PORT=1514
    networks:
      splunk:
        aliases:
          - hw_forwarder
    labels:
      splunk.cluster: "hw_forwarder"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-lb-template:
    build: ./shc-lb-template/
    container_name: shc-lb-template
    hostname: shc-lb-template
    depends_on:
      - consul
    environment: 
      - CONSUL_HOST=consul:8500
      - CONSUL_DC=dc
      - CONSUL_DOMAIN=splunk
    labels:
      splunk.cluster: "shc-lb-template"
    networks:
      splunk:
        aliases:
          - shc-lb-template
    restart: always
    volumes:
      - shc_lb_template:/usr/local/etc/haproxy/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  shc-lb:
    image: haproxy:1.6.6
    container_name: shc-lb
    hostname: shc-lb
    depends_on:
      - consul
      - shc-lb-template
      - hw_forwarder
    labels:
      splunk.cluster: "shc-lb"
    networks:
      splunk:
        aliases:
          - shc-lb
    restart: always
    ports:
      - 8000
    volumes:
      - shc_lb_template:/usr/local/etc/haproxy/
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

volumes:
  shc_lb_template:
    driver: local

networks:
  splunk: