version: '2'
services:
  # Cluster Master will contain all roles, including Cluster Master,
  # SHC Deployer, License Master, Deployment Server
  cluster-master:
    build: ./node/
    container_name: cluster-master
    hostname: cluster-master
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - INIT_CLUSTER_REPLICATION_FACTOR=1
      - INIT_CLUSTER_SEARCH_FACTOR=1
      - SPLUNK_ROLES=cluster_master
    labels:
      splunk.cluster: "cluster-master"
    networks:
      splunk:
        aliases:
          - cluster-master
          - license-master
          - shc-deployer
          - deployment-server
    ports:
      - 8089
      - 8000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  # SHC Member
  shc-member:
    build: ./node/
    depends_on:
      - cluster-master
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - INIT_SHC_REPLICATION_FACTOR=3
      - SPLUNK_ROLES=shc_member
    labels:
      splunk.cluster: "shc-member"
    networks:
      - splunk
    ports:
      - 8000
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

  # Cluster Slave
  cluster-member:
    build: ./node/
    depends_on:
      - cluster-master
    environment: 
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_ROLES=cluster_slave
    labels:
      splunk.cluster: "cluster-member"
    networks:
      - splunk
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "5"

networks:
  splunk: